### ISSUE TITLE
Override default spacer block with Flexible spacer.

### ISSUE THREAD

**Issue by officialsabbir** [t-hamano/flexible-spacer-block#60]
Hey there,

On my website, the default "spacer" block remains hidden after the page is loaded, and I've been struggling to resolve it. However, I stumbled upon your plugin, and it works perfectly! I've successfully replaced the default spacer block with it. Now, I'm aiming to automatically override all default "spacer" blocks with Flexible Spacer without manual intervention. Please tell me how can i do it?

Regards
Sabbir

**Comment by t-hamano** [comment]
Hi, 

One way would be to replace the default spacer block HTML in your database with this HTML all at once.
Or maybe you can parse the post content with PHP and replace specific blocks.

In any case, this issue is not specific to my block, so I will close this issue.
